### ISSUE TITLE
`from_json': undefined local variable or method `parsed_json' for class AssemblyAI::Transcripts::Transcript (NameError)

### ISSUE THREAD

**Issue by Swimburger** [AssemblyAI/assemblyai-ruby-sdk#31]
I'm running this code:

```rb
require 'dotenv/load'
require 'assemblyai'

client = AssemblyAI::Client.new(
  api_key: ENV['ASSEMBLYAI_API_KEY']
)

transcript = client.transcripts.transcribe(
  audio_url: 'https://storage.googleapis.com/aai-web-samples/5_common_sports_injuries.mp3',
  speech_model: AssemblyAI::Transcripts::SpeechModel::NANO
)

raise transcript.error unless transcript.error.nil?

puts transcript.text
```
Which throws this error

```plaintext
/Users/niels/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/assemblyai-1.0.0.pre.beta.9/lib/assemblyai/transcripts/types/transcript.rb:453:in `from_json': undefined local variable or method `parsed_json' for class AssemblyAI::Transcripts::Transcript (NameError)

        words = parsed_json["words"]&.map do |v|
                ^^^^^^^^^^^
	from /Users/niels/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/assemblyai-1.0.0.pre.beta.9/lib/assemblyai/transcripts/client.rb:160:in `submit'
	from /Users/niels/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/assemblyai-1.0.0.pre.beta.9/lib/assemblyai/transcripts/polling_client.rb:76:in `transcribe'
	from /Users/niels/RubymineProjects/AssemblyAISample/transcribe.rb:9:in `<main>'
```

**Comment by armandobelardo** [comment]
This is resolved in the latest version of the generator, which has been used to regenerate this SDK!
